---
# tasks file for role_sample_with_collections
- name: "echo name of role"
  debug:
    msg: "You are running role_sample_with_collections"

- name: "Configurable Cisco NXOS Backup Path"
  cisco.nxos.nxos_config:
    backup: yes
    backup_options:
      dir_path: "/etc/ansible/backups/nxos/{{ inventory_hostname }}"
      filename: backup.cfg
